## GlucoGuard Analytics: Hospital Readmission Prediction of Diabetic Patient

Team members
1. Aurelia Maria Ozora
2. Brian Anyau Nyeko Moini
3. Dharani Ranasinghe
4. Muna Mohammad Ahmad Shati
5. Pau Garcia I Morales
6. Prabhu Raj Singh

## The Dataset
The diabetic_data dataset contains records of diabetic patients' hospital admissions, including characteristics of admitted patients, their medication history, and related data such as the medical specialty of the admitting physician and readmission status. The dataset is from the UCI Repository (https://archive.ics.uci.edu/dataset/34/diabetes)

the dataset have 50 features and 101765 observations.

The dataset contains 9 numerical features named: 
- weight                              
- time_in_hospital
- num_lab_procedures
- num_procedures
- num_medications
- number_outpatient
- number_emergency
- number_inpatient
- number_diagnoses

The dataset contains 41 categorical features: 
- encounter_id                       Nominal
- patient_nbr                        Nominal
- race                               Nominal
- gender                             Nominal
- age                                Ordinal 
- admission_type_id                  Nominal
- discharge_disposition_id           Nominal
- admission_source_id                Nominal
- payer_code                         Nominal
- medical_specialty                  Nominal
- diag_1                             Nominal
- diag_2                             Nominal
- diag_3                             Nominal
- max_glu_serum                      Ordinal 
- A1Cresult                          Ordinal 
- metformin                          Nominal
- repaglinide                        Nominal
- nateglinide                        Nominal
- chlorpropamide                     Nominal
- glimepiride                        Nominal
- acetohexamide                      Nominal
- glipizide                          Nominal
- glyburide                          Nominal
- tolbutamide                        Nominal
- pioglitazone                       Nominal
- rosiglitazone                      Nominal
- acarbose                           Nominal
- miglitol                           Nominal
- troglitazone                       Nominal
- tolazamide                         Nominal
- examide                            Nominal
- citoglipton                        Nominal
- insulin                            Nominal
- glyburide-metformin                Nominal
- glipizide-metformin                Nominal
- glimepiride-pioglitazone           Nominal
- metformin-rosiglitazone            Nominal
- metformin-pioglitazone             Nominal
- change                             Nominal
- diabetesMed                        Nominal
- readmitted                         Nominal

A total of 26 binary features are included in the dataset. We can diferentiate between those determining "steady" or "non-steady" or "change" vs. "no-change" states and the "yes" or "no" features: 
- metformin                          
- repaglinide                        
- nateglinide                        
- chlorpropamide                     
- glimepiride                        
- acetohexamide
- glipizide  
- glyburide                          
- tolbutamide                        
- pioglitazone                       
- rosiglitazone                      
- acarbose                           
- miglitol                           
- troglitazone                       
- tolazamide                         
- examide                            
- citoglipton                        
- insulin                        
- glyburide-metformin                
- glipizide-metformin                
- glimepiride-pioglitazone           
- metformin-rosiglitazone            
- metformin-pioglitazone             
- change          
- diabetesMed                       
- readmitted

## Load the dataset

In [1]:
# Import library
import pandas as pd
import numpy as np

In [2]:
# Load the dataset
df = pd.read_csv("diabetic_data.csv")
df.head()

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),?,6,25,1,1,...,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),?,1,1,7,3,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),?,1,1,7,2,...,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),?,1,1,7,2,...,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),?,1,1,7,1,...,No,Steady,No,No,No,No,No,Ch,Yes,NO

In [3]:
# Select all columns from the specific row with index `4`
df.loc[4]   # `loc[]` iterates over valid values of the index

encounter_id                    16680
patient_nbr                  42519267
race                        Caucasian
gender                           Male
age                           [40-50)
weight                              ?
admission_type_id                   1
discharge_disposition_id            1
admission_source_id                 7
time_in_hospital                    1
payer_code                          ?
medical_specialty                   ?
num_lab_procedures                 51
num_procedures                      0
num_medications                     8
number_outpatient                   0
number_emergency                    0
number_inpatient                    0
diag_1                            197
diag_2                            157
diag_3                            250
number_diagnoses                    5
max_glu_serum                     NaN
A1Cresult                         NaN
metformin                          No
repaglinide                        No
nateglinide                        No
chlorpropamide                     No
glimepiride                        No
acetohexamide                      No
glipizide                      Steady
glyburide                          No
tolbutamide                        No
pioglitazone                       No
rosiglitazone                      No
acarbose                           No
miglitol                           No
troglitazone                       No
tolazamide                         No
examide                            No
citoglipton                        No
insulin                        Steady
glyburide-metformin                No
glipizide-metformin                No
glimepiride-pioglitazone           No
metformin-rosiglitazone            No
metformin-pioglitazone             No
change                             Ch
diabetesMed                       Yes
readmitted                         NO
Name: 4, dtype: object

## Preprocessing

### 1. Check the size of the dataset

In [4]:
# Total size of the dataset
df.shape

(101766, 50)

### 2. Handle missing values:
- Check for missing values: In this dataset, there are two types of missing values: unknown values represented by '?' and rows with None/NaN.
- Handle missing values in the features max_glu_serum and A1Cresult.
- Remove features with a significant amount of missing values: weight, payer_code, and medical_specialty.
- Delete rows with missing values.
- Recheck the size of the dataset to ensure that data deletion does not lead to a significant loss of information.

In [5]:
# Count missing values
# Get the number of rows that contain '?' for each feature
missing_value_counts = df[df == '?'].count()

# Display the result
print(missing_value_counts)

encounter_id                    0
patient_nbr                     0
race                         2273
gender                          0
age                             0
weight                      98569
admission_type_id               0
discharge_disposition_id        0
admission_source_id             0
time_in_hospital                0
payer_code                  40256
medical_specialty           49949
num_lab_procedures              0
num_procedures                  0
num_medications                 0
number_outpatient               0
number_emergency                0
number_inpatient                0
diag_1                         21
diag_2                        358
diag_3                       1423
number_diagnoses                0
max_glu_serum                   0
A1Cresult                       0
metformin                       0
repaglinide                     0
nateglinide                     0
chlorpropamide                  0
glimepiride                     0
acetohexamide                   0
glipizide                       0
glyburide                       0
tolbutamide                     0
pioglitazone                    0
rosiglitazone                   0
acarbose                        0
miglitol                        0
troglitazone                    0
tolazamide                      0
examide                         0
citoglipton                     0
insulin                         0
glyburide-metformin             0
glipizide-metformin             0
glimepiride-pioglitazone        0
metformin-rosiglitazone         0
metformin-pioglitazone          0
change                          0
diabetesMed                     0
readmitted                      0
dtype: int64

In [6]:
# Check for NaN missing values in the DataFrame
missing_values = df.isnull().sum()

# Print the number of missing values for each column
print(missing_values)

encounter_id                    0
patient_nbr                     0
race                            0
gender                          0
age                             0
weight                          0
admission_type_id               0
discharge_disposition_id        0
admission_source_id             0
time_in_hospital                0
payer_code                      0
medical_specialty               0
num_lab_procedures              0
num_procedures                  0
num_medications                 0
number_outpatient               0
number_emergency                0
number_inpatient                0
diag_1                          0
diag_2                          0
diag_3                          0
number_diagnoses                0
max_glu_serum               96420
A1Cresult                   84748
metformin                       0
repaglinide                     0
nateglinide                     0
chlorpropamide                  0
glimepiride                     0
acetohexamide                   0
glipizide                       0
glyburide                       0
tolbutamide                     0
pioglitazone                    0
rosiglitazone                   0
acarbose                        0
miglitol                        0
troglitazone                    0
tolazamide                      0
examide                         0
citoglipton                     0
insulin                         0
glyburide-metformin             0
glipizide-metformin             0
glimepiride-pioglitazone        0
metformin-rosiglitazone         0
metformin-pioglitazone          0
change                          0
diabetesMed                     0
readmitted                      0
dtype: int64

In [7]:
# List all possible values in max_glu_serum
print(df['max_glu_serum'].unique())

# List all possible values in A1Cresult
print(df['A1Cresult'].unique())

[nan '>300' 'Norm' '>200']
[nan '>7' '>8' 'Norm']

### Missing values
We have identified several features with significant missing values: weight, payer_code, medical_specialty, max_glu_serum, and A1Cresult.

For the features weight, payer_code, and medical_specialty, we have decided to remove them. Although these features might be related to patient readmission, they are not clinically relevant. In contrast, max_glu_serum and A1Cresult are clinically important, and simply removing these features would be detrimental. 

Before deciding on the best strategy for handling the data, we need to understand the nature of these attributes: 

**max_glu_serum** refers to the maximum glucose serum test result recorded for a patient. Glucose serum tests measure the concentration of glucose (sugar) in the blood and are commonly used to diagnose and monitor diabetes. Some values, such as '300' or '200', create a lack of visibility for this variable. Therefore, imputation is not advisable as it could introduce significant bias. Consequently, all "none" results will be interpreted as the test not being performed or not measured. 

**A1Cresult** refers to the result of the A1C test, also known as the hemoglobin A1c test. This test measures the average blood sugar level over the past 2 to 3 months and is commonly used to diagnose and monitor diabetes. If the test result is normal (indicating good blood sugar control), it is represented as 'Norm'. Abnormal results (indicating poor blood sugar control) are represented by specific values indicating different levels of abnormality, such as ">7%" or ">8%", which typically represent elevated A1C levels associated with diabetes. NaN will also be interpreted as not measured.

Thus, we decided to transform the values in these two features. 
For **max_glu_serum**, values '>200' will be assigned as 'Elevated', values '>300' will be assigned as 'High', 'Norm' will be assigned the value 'Normal', and NaN will be assigned the value 'Not measured'. 
For **A1Cresult**, values '>7' and '>8' will be assigned as 'High', 'Norm' will be assigned the value 'Normal', and NaN will be assigned the value 'Not measured'.

In [8]:
def transform_A1Cresult(value):
    if value == 'Norm':
        return 'Normal'
    elif value in ['>7', '>8']:
        return 'High'
    else:
        return 'Not measured'

def transform_max_glu_serum(value):
    if value == 'Norm':
        return 'Normal'
    elif value == '>300':
        return 'High'
    elif value == '>200':
        return 'Elevated'
    else:
        return 'Not measured'
    
df['max_glu_serum_transformed'] = df['max_glu_serum'].apply(transform_max_glu_serum)
df['A1Cresult_transformed'] = df['A1Cresult'].apply(transform_A1Cresult)

# Verify the transformation
df.head()

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted,max_glu_serum_transformed,A1Cresult_transformed
0,2278392,8222157,Caucasian,Female,[0-10),?,6,25,1,1,...,No,No,No,No,No,No,No,NO,Not measured,Not measured
1,149190,55629189,Caucasian,Female,[10-20),?,1,1,7,3,...,No,No,No,No,No,Ch,Yes,>30,Not measured,Not measured
2,64410,86047875,AfricanAmerican,Female,[20-30),?,1,1,7,2,...,No,No,No,No,No,No,Yes,NO,Not measured,Not measured
3,500364,82442376,Caucasian,Male,[30-40),?,1,1,7,2,...,No,No,No,No,No,Ch,Yes,NO,Not measured,Not measured
4,16680,42519267,Caucasian,Male,[40-50),?,1,1,7,1,...,No,No,No,No,No,Ch,Yes,NO,Not measured,Not measured

In [9]:
# Delete original columns
df = df.drop(['max_glu_serum', 'A1Cresult'], axis=1) 
df.shape

(101766, 50)

In [10]:
# Delete the features that have a lot of missing values
columns_to_delete = ['weight', 'payer_code', 'medical_specialty']
df = df.drop(columns=columns_to_delete)

# Verify that the columns were deleted
df.shape

(101766, 47)

In [11]:
# Delete rows that has '?'values
df.replace('?', np.nan, inplace=True)
df = df.dropna()

# Check the size of the dataset after handling missing values
df.shape

(98053, 47)

### 3. Assigning correct datatypes
- Check the datatypes of all features.
- Change object datatypes to categorical for features with nominal values.
- Assign order to values and convert object datatypes to categorical for features with ordinal values.

In [12]:
# Check datatypes
df.dtypes

encounter_id                  int64
patient_nbr                   int64
race                         object
gender                       object
age                          object
admission_type_id             int64
discharge_disposition_id      int64
admission_source_id           int64
time_in_hospital              int64
num_lab_procedures            int64
num_procedures                int64
num_medications               int64
number_outpatient             int64
number_emergency              int64
number_inpatient              int64
diag_1                       object
diag_2                       object
diag_3                       object
number_diagnoses              int64
metformin                    object
repaglinide                  object
nateglinide                  object
chlorpropamide               object
glimepiride                  object
acetohexamide                object
glipizide                    object
glyburide                    object
tolbutamide                  object
pioglitazone                 object
rosiglitazone                object
acarbose                     object
miglitol                     object
troglitazone                 object
tolazamide                   object
examide                      object
citoglipton                  object
insulin                      object
glyburide-metformin          object
glipizide-metformin          object
glimepiride-pioglitazone     object
metformin-rosiglitazone      object
metformin-pioglitazone       object
change                       object
diabetesMed                  object
readmitted                   object
max_glu_serum_transformed    object
A1Cresult_transformed        object
dtype: object

In [13]:
# Assign correct datatypes
# Convert the nominal variables
categorical_columns = ['race', 'gender', 'diag_1', 'diag_2', 'diag_3', 'metformin', 'repaglinide', 
                       'nateglinide', 'chlorpropamide', 'glimepiride','acetohexamide', 'glipizide', 
                       'glyburide', 'tolbutamide', 'pioglitazone', 'rosiglitazone','acarbose', 
                       'miglitol', 'troglitazone', 'tolazamide', 'examide', 'citoglipton', 'insulin',
                       'glyburide-metformin', 'glipizide-metformin', 'glimepiride-pioglitazone',
                       'metformin-rosiglitazone','metformin-pioglitazone', 'change', 'diabetesMed',
                       'readmitted']
df[categorical_columns] = df[categorical_columns].astype('category')

df.dtypes

encounter_id                    int64
patient_nbr                     int64
race                         category
gender                       category
age                            object
admission_type_id               int64
discharge_disposition_id        int64
admission_source_id             int64
time_in_hospital                int64
num_lab_procedures              int64
num_procedures                  int64
num_medications                 int64
number_outpatient               int64
number_emergency                int64
number_inpatient                int64
diag_1                       category
diag_2                       category
diag_3                       category
number_diagnoses                int64
metformin                    category
repaglinide                  category
nateglinide                  category
chlorpropamide               category
glimepiride                  category
acetohexamide                category
glipizide                    category
glyburide                    category
tolbutamide                  category
pioglitazone                 category
rosiglitazone                category
acarbose                     category
miglitol                     category
troglitazone                 category
tolazamide                   category
examide                      category
citoglipton                  category
insulin                      category
glyburide-metformin          category
glipizide-metformin          category
glimepiride-pioglitazone     category
metformin-rosiglitazone      category
metformin-pioglitazone       category
change                       category
diabetesMed                  category
readmitted                   category
max_glu_serum_transformed      object
A1Cresult_transformed          object
dtype: object

In [14]:
# Change age datatype to ordinal
# List all possible values in age
print(df['age'].unique())

['[10-20)' '[20-30)' '[30-40)' '[40-50)' '[50-60)' '[60-70)' '[70-80)'
 '[80-90)' '[90-100)' '[0-10)']

In [15]:
# Define the order of age ranges
age_order = ['[0-10)', '[10-20)', '[20-30)', '[30-40)', '[40-50)', '[50-60)', '[60-70)', '[70-80)', '[80-90)', '[90-100)']

# Define the order for max_glu_serum_transformed
max_glu_order = ['Not measured', 'Normal', 'Elevated', 'High']

# Define the order for A1Cresult_transformed
A1C_order = ['Not measured', 'Normal', 'High']

# Convert to ordinal categorical type
df['age'] = pd.Categorical(df['age'], categories=age_order, ordered=True)
df['max_glu_serum_transformed'] = pd.Categorical(df['max_glu_serum_transformed'], categories=max_glu_order, ordered=True)
df['A1Cresult_transformed'] = pd.Categorical(df['A1Cresult_transformed'], categories=A1C_order, ordered=True)

df.dtypes

encounter_id                    int64
patient_nbr                     int64
race                         category
gender                       category
age                          category
admission_type_id               int64
discharge_disposition_id        int64
admission_source_id             int64
time_in_hospital                int64
num_lab_procedures              int64
num_procedures                  int64
num_medications                 int64
number_outpatient               int64
number_emergency                int64
number_inpatient                int64
diag_1                       category
diag_2                       category
diag_3                       category
number_diagnoses                int64
metformin                    category
repaglinide                  category
nateglinide                  category
chlorpropamide               category
glimepiride                  category
acetohexamide                category
glipizide                    category
glyburide                    category
tolbutamide                  category
pioglitazone                 category
rosiglitazone                category
acarbose                     category
miglitol                     category
troglitazone                 category
tolazamide                   category
examide                      category
citoglipton                  category
insulin                      category
glyburide-metformin          category
glipizide-metformin          category
glimepiride-pioglitazone     category
metformin-rosiglitazone      category
metformin-pioglitazone       category
change                       category
diabetesMed                  category
readmitted                   category
max_glu_serum_transformed    category
A1Cresult_transformed        category
dtype: object

### Save to a new file

In [16]:
# Save the processed dataframe in `./diabetes_clean.csv`
df.to_csv("./diabetes_clean.csv",
                    index=False)